apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env: 
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef: 
                name: db-secret
                key: DB_USERNAME
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          - name: MYSQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_DATABASE
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-secret
                key: DB_PASSWORD
          volumeMounts:
            - name: mysql-storage
              mountPath: /data
      nodeSelector:
          kubernetes.io/hostname: minikube
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: mysql-pvc


        