apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
  namespace: argocd
data:
  avp.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      allowConcurrency: true
      discover:
        find:
          command: ["sh", "-c", "echo 'init step'"]
      generate:
        command: ["argocd-vault-plugin"]
        args: ["generate", "./"]
      lockRepo: false
