services:
  api-gateway:
    # build:
    #   context: .
    #   args:
    #     SERVICE: api-gateway
    #     PORT: ${SERVER_PORT}
    image: ribun/task-management-api-gateway:v1.0 #ribun/octaltask-backend-api-gateway:${TAG:-dev}
    container_name: octaltask-backend-api-gateway
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env
 
  auth-service:
    # build:
    #   context: .
    #   args:
    #     SERVICE: auth-service
    #     PORT: ${AUTH_PORT}
    image: ribun/task-management-auth-service:v1.0
    container_name: octaltask-backend-auth-service
    ports:
      - "${AUTH_PORT}:${AUTH_PORT}"
    env_file:
      - .env
    depends_on:
      - api-gateway

  task-service:
    # build:
    #   context: .
    #   args:
    #     SERVICE: task-service
    #     PORT: ${TASK_PORT}
    image: ribun/task-management-task-service:v1.0
    container_name: octaltask-backend-task-service
    ports:
      - "${TASK_PORT}:${TASK_PORT}"
    env_file:
      - .env
    depends_on:
      - auth-service
    
  user-service:
    # build:
    #   context: .
    #   args:
    #     SERVICE: user-service
    #     PORT: ${USER_PORT}
    image:  ribun/task-management-user-service:v1.0
    container_name: octaltask-backend-user-service
    ports:
      - "${USER_PORT}:${USER_PORT}"
    env_file:
      - .env
    depends_on:
      - api-gateway
