apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-secret
  namespace: mysql
data:
  DB_USERNAME: <path:secret/dev/database#DB_USERNAME>
  DB_PASSWORD: <path:secret/dev/database#DB_PASSWORD>
  DB_DATABASE: <path:secret/dev/database#DB_DATABASE>
  