apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_AUTH_TYPE: approle
  VAULT_ADDR: http://vault.netsena.io.vn:8200
  AVP_ROLE_ID: 4ffb956d-1f5c-f370-9c8c-4dfb0b7de36b
  AVP_SECRET_ID: e609dd10-f555-211b-0e72-9a7d0ad8c105