apiVersion: v1
kind: Secret
metadata:
  name: argocd-vault-plugin-credentials
  namespace: argocd
type: Opaque
stringData:
  AVP_AUTH_TYPE: approle
  VAULT_ADDR: <vault.example.com>
  AVP_ROLE_ID: <secret-role-id>
  AVP_SECRET_ID: <secret-id-vault>