apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend-dev
data:
  MAIL_HOST: <path:secret/data/dev/backend#MAIL_HOST>
  MAIL_PORT: <path:secret/data/dev/backend#MAIL_PORT>
  MAIL_USER: <path:secret/data/dev/backend#MAIL_USER>
  MAIL_PASSWORD: <path:secret/data/dev/backend#MAIL_PASSWORD>
  MAIL_FROM: <path:secret/data/dev/backend#MAIL_FROM>
  DB_TYPE: <path:secret/data/dev/backend#DB_TYPE>
  DB_HOST: <path:secret/data/dev/backend#DB_HOST>
  DB_PORT: <path:secret/data/dev/backend#DB_PORT>
  DB_USERNAME: <path:secret/data/dev/backend#DB_USERNAME>
  DB_PASSWORD: <path:secret/data/dev/backend#DB_PASSWORD>
  DB_DATABASE: <path:secret/data/dev/backend#DB_DATABASE>
  DB_ROOT_PASSWORD: <path:secret/data/dev/backend#DB_ROOT_PASSWORD>
  JWT_SECRET: <path:secret/data/dev/backend#JWT_SECRET>
  TOKEN_EXPIRE_TIME: <path:secret/data/dev/backend#TOKEN_EXPIRE_TIME>
  SERVER_PORT: <path:secret/data/dev/backend#SERVER_PORT>
  AUTH_PORT: <path:secret/data/dev/backend#AUTH_PORT>
  TASK_PORT: <path:secret/data/dev/backend#TASK_PORT>
  USER_PORT: <path:secret/data/dev/backend#USER_PORT>
  FRONTEND_BASE_URL: <path:secret/data/dev/backend#FRONTEND_BASE_URL>
  CLIENT_GRPC_AUTH_URL: <path:secret/data/dev/backend#CLIENT_GRPC_AUTH_URL>
  CLIENT_GRPC_TASK_URL: <path:secret/data/dev/backend#CLIENT_GRPC_TASK_URL>
  CLIENT_GRPC_USER_URL: <path:secret/data/dev/backend#CLIENT_GRPC_USER_URL>
  GRPC_SERVER_AUTH_URL: <path:secret/data/dev/backend#GRPC_SERVER_AUTH_URL>
  GRPC_SERVER_TASK_URL: <path:secret/data/dev/backend#GRPC_SERVER_TASK_URL>
  GRPC_SERVER_USER_URL: <path:secret/data/dev/backend#GRPC_SERVER_USER_URL>
  GRPC_LISTEN_AUTH_URL: <path:secret/data/dev/backend#GRPC_LISTEN_AUTH_URL>
  GRPC_LISTEN_TASK_URL: <path:secret/data/dev/backend#GRPC_LISTEN_TASK_URL>
  GRPC_LISTEN_USER_URL: <path:secret/data/dev/backend#GRPC_LISTEN_USER_URL>
  TAG: <path:secret/data/dev/backend#TAG>