apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-services
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/RibunLoc/DevOps-work-management-web-platform.git
    targetRevision: develop
    path: k8s-deployment/backend

  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
