apiVersion: apps/v1
kind: Deployment
metadata:
  name: octaltask-web-front
  namespace: frontend-dev
  labels:
    app: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: frontend-container
          image: ribun/taskmanagement_frontend:v2.0
          ports:
            - containerPort: 5173
