apiVersion: v1
kind: Service
metadata:
  name: web-frontend-svc
  namespace: frontend-dev
spec:
  type: NodePort
  selector:
    app: web-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5173
  type: ClusterIP