# Ref - https://github.com/argoproj/argo-helm/blob/main/charts/argo-cd/values.yaml
server:
  service:
    type: ClusterIP
    ports:
      http: 80
    servicePortHttp: 80

  ingress:
    enabled: true
    ingressClassName: alb
    servicePort: http
    annotations:
      kubernetes.io/ingress.class: alb
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: ip
      alb.ingress.kubernetes.io/backend-protocol: HTTP
      alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
      alb.ingress.kubernetes.io/group.name: alb-ops-group
      alb.ingress.kubernetes.io/load-balancer-name: alb-ops
      alb.ingress.kubernetes.io/healthcheck-path: "/healthz"
      alb.ingress.kubernetes.io/healthcheck-port: "traffic-port"
      alb.ingress.kubernetes.io/success-codes: "200"
  
    hostname: "argocd.netsena.io.vn"
    path: /
    pathType: Prefix
    tls: false

configs:
  secret:
    argocdServerAdminPassword: $2a$10$WB6tAqyvGrhooHauWJOfqeFaWdVekKwsasIAZwNj7mGc8frYgN67q
  params:
    server.insecure: true

controller:
  enableStatefulSet: true

applicationSet:
  enabled: true

dex:
  enabled: false