# Ref - https://github.com/longhorn/longhorn/blob/master/chart/values.yaml
ingress:
  enabled: true
  ingressClassName: alb
  host: longhorn.netsena.io.vn
  path: /
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/backend-protocol: HTTP
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
    alb.ingress.kubernetes.io/group.name: alb-ops-group
    alb.ingress.kubernetes.io/load-balancer-name: alb-ops